FROM golang:1.25 AS builder
WORKDIR /src
COPY . .
RUN go build -o /out/upstream ./cmd/upstream
RUN go build -o /out/healthcheck ./cmd/healthcheck

FROM gcr.io/distroless/base-debian12
COPY --from=builder /out/upstream /upstream
COPY --from=builder /out/healthcheck /healthcheck
EXPOSE 8081
ENTRYPOINT ["/upstream"]
